language: go
go:
- 1.11.x
- 1.12.x
addons:
  apt:
    packages:
    - rpm
env:
- GO111MODULE=off
go_import_path: github.com/nats-io/nats-server
install:
- go get github.com/nats-io/nats.go/
- go get github.com/nats-io/nkeys
- go get github.com/nats-io/jwt
- go get -u honnef.co/go/tools/cmd/staticcheck
- go get -u github.com/client9/misspell/cmd/misspell
before_script:
- EXCLUDE_VENDOR=$(go list ./... | grep -v "/vendor/")
- go build
- $(exit $(go fmt $EXCLUDE_VENDOR | wc -l))
- go vet $EXCLUDE_VENDOR
- misspell -error -locale US $EXCLUDE_VENDOR
- staticcheck $EXCLUDE_VENDOR
script:
- go test -i $EXCLUDE_VENDOR
- go test -run=TestNoRace $EXCLUDE_VENDOR
- if [[ "$TRAVIS_GO_VERSION" =~ 1.12 ]]; then ./scripts/cov.sh TRAVIS; else go test -v -race -p=1 --failfast $EXCLUDE_VENDOR; fi

deploy:
  provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ 1.12

notifications:
  email: false
